version: '2'
services:
  web:
    image: nginx:1-alpine
    ports:
      - "8080:80"
    depends_on:
      - app
    volumes_from:
      - app
    volumes:
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
  app:
    build: .
    depends_on:
      - db
    volumes:
      - ./docker/wp-config.php:/var/www/html/wp-config.php
  db:
    image: mysql:5.7
    env_file: ./docker/.env
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data: